build-yaml2json2yaml:
  script: 
    - echo "${HOSTNAME}" $(pwd) $(date)
    - yum -y -q install make
    - make init save build
    - bin/slack-status yaml2json2yaml-build ${?}
    - ./dockerize
    - bin/slack-status yaml2json2yaml-dockerize ${?}
  only:
    - master
  tags:
    - shell
    - ssh
