stages:
  - build
  
variables:
  gitlab_user: root
  gitlab_host: 128.107.15.211
  config_url:  http://ci-secret-config/slackurl
  secret_url:  http://ci-secret-config/kubeconfig
  deploy_yaml: http://ci-secret-config/deploy.yaml

build-yaml2json2yaml:
  stage: build
  script: 
    - echo "${HOSTNAME}" $(pwd) $(date)
    # - yum -y -q install make
    # - export GOPATH=/go
    # - GO15VENDOREXPERIMENT=1 go get --ldflags '-s -w' github.com/tools/godep
    # - GO15VENDOREXPERIMENT=1 go install --ldflags '-s -w' github.com/tools/godep
    - export PATH=${GOPATH}/bin:${PATH}
    - go get github.com/davidwalter0/transform
    - ./build
    - rc=$?
    - bin/slack-status --step=${step} --gitlab-host=${gitlab_host} --gitlab-user=${gitlab_user} --slack-url=${config_url} --rc=${?}
    - ./dockerize
    - rc=$?
    - bin/slack-status --step=${step} --gitlab-host=${gitlab_host} --gitlab-user=${gitlab_user} --slack-url=${config_url} --rc=${?}
  only:
    - master
  tags:
    - shell
    - ssh
